### ISSUE TITLE
Slash double asterisk slash suppose to remove the GOOD CODE.

### ISSUE THREAD

**Issue by dmitryou** [jnthnjns/grunt-stripcomments#27]
Hi,
I faced wrong behavior of module.
I use :
```javascript
options: {
				singleline: true,
				multiline: true
			},
```
If following lines exists in code it will remove it:
/asteriskAsterisk/
CODE will REMOVED!
/asteriskAsterisk/

![screenshot101](https://cloud.githubusercontent.com/assets/13177336/23662540/a16f7d1e-0358-11e7-8eca-e5b760c0cdd6.png)

Except of it things works awesome!

**Comment by jnthnjns** [comment]
@dmitryou Thank you for bringing this to my attention.

I will have to play around with it and write some tests for it. In the meantime you can insert a space between the asterisks and it will remove correctly.

Example:

```javascript
/* */
This code should be preserved
/* */
```

**Comment by dmitryou** [comment]
Yep, my solution was to remove this kind of comments :)
Thanks
